### ISSUE TITLE
 obsoletions: transporter activity terms for 7 specific xenobiotic compound

### ISSUE THREAD

**Issue by raymond91125** [geneontology/simple-report-system#35]
GO:0015898 amiloride transport | MGI 1
GO:0036253 response to amiloride | RGD 1
GO:0036254 cellular response to amiloride | ComplexPortal 13
GO:0072755 cellular response to benomyl | UniProt 1

**Comment by kltm** [comment]
@raymond91125 If you want the reports to run, you have to label before creating the issue.

**Comment by raymond91125** [comment]
I cannot find a way to enter anything to the right, Assignees, Labels, etc. There are no gear wheels there.
![Screenshot from 2023-01-31 17-41-15](https://user-images.githubusercontent.com/619520/215924184-5b60db57-72b4-41a6-b8d8-eaec98eef880.png)

**Comment by raymond91125** [comment]
compare to
![Screenshot from 2023-01-31 17-43-47](https://user-images.githubusercontent.com/619520/215924545-873222e5-1338-4c7d-8d00-132668f99c58.png)

**Comment by kltm** [comment]
@raymond91125 Let me check your permissions.

**Comment by kltm** [comment]
@raymond91125 Okay, refresh and give it another try.
