### ISSUE TITLE
Review annotations to 3-hydroxyacyl-CoA dehydratase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/simple-report-system#43]
GO:0080023 (3R)-3-hydroxyacyl-CoA dehydratase activity -> 6 EXP
GO:0003859 (3R)-3-hydroxybutyryl-CoA dehydratase activity -> 1 EXP
GO:0102158 very-long-chain (3R)-3-hydroxyacyl-CoA dehydratase activity -> 0 EXP, all IEAs RHEA/EC
GO:0016508 long-chain-enoyl-CoA hydratase activity -> 7 EXP

**Comment by kltm** [comment]
@pgaudet You had me move this over to the go-annotation repo? Do you want me to close this out or archive it?

**Comment by kltm** [comment]
Failed anyways, so closing.
